### ISSUE TITLE
Update GitHub Actions permissions

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/devcontainer-features#2]
> Previously, GitHub Actions gets a GITHUB_TOKEN with both read/write permissions by default whenever Actions is enabled on a repository.
> As a default, this is too permissive, so to improve security we would like to change the default going forward to a read-only token. You can still flip it to read/write if needed.
>
> This change will not impact any existing enterprises, organizations or repositories. Here is how the defaults are set going forward.
>
> - Enterprises: New enterprises will have read-only token.
> - Organizations owned by Enterprise: New organizations will inherit the permissions from parent enterprise.
> - Organizations not owned by Enterprise: New organizations will have read-only token.
> - Repositories owned by organization: New repositories will inherit permissions from parent organization.
> - Repositories owned by personal account: New repositories will have read-only token.

&mdash; https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

Here's the docs on how to specify perms: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Comment by jcbhmr** [comment]
This has come back to bite me already 🤷‍♂️

![image](https://user-images.githubusercontent.com/61068799/221326420-f43b361b-e9f1-4e88-b03f-851fe585f842.png)
https://github.com/jcbhmr/devcontainer-features/actions/runs/4267459350/jobs/7429085875

**Comment by jcbhmr** [comment]
So I need to:

- [ ] Make it so that the devcontainer publish gets the packages write scope
- [ ] Make it so that the wiki action gets the write repo scope AND the wiki scope (whatever it's called)

**Comment by jcbhmr** [comment]
Turns out there is no wiki specific one that I could find?

```yml
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none
```

I think it must be the `contents: write` which does it?

**Comment by jcbhmr** [comment]
Yep for the wiki!

![image](https://user-images.githubusercontent.com/61068799/221326668-21d9f8bf-9fd6-4a83-b365-f3c9ffbbfc2e.png)

**Comment by jcbhmr** [comment]
The publish action still doesn't work 🤔

https://github.com/devcontainers/feature-starter/blob/0937a6939a8c9c75a54171981fb8fc169586109b/.github/workflows/release.yaml#L5-L14

```yml
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v3
```

Maybe it has to be contents: write too?
